# Generated by Django 4.2.6 on 2023-10-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Departamento', models.CharField(max_length=200)),
                ('Autor', models.CharField(max_length=200)),
                ('Quantidade_páginas', models.PositiveSmallIntegerField()),
                ('idioma', models.CharField(max_length=200)),
            ],
        ),
    ]
