# Generated by Django 4.2.6 on 2023-10-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='Nome_do_Livro',
            field=models.CharField(default='it', max_length=200),
            preserve_default=False,
        ),
    ]
